### ISSUE TITLE
LICENSE is empty

### ISSUE THREAD

**Issue by jeffgdotorg** [jasonyates/netbox-circuitmaintenance#21]
**Plugin version**
0.3.0

**NetBox version**
3.7.3

**Describe the bug**
The top-level `LICENSE` file in the `netbox-circuitmaintenance` repository is empty. As a result, users have no way of knowing the terms that apply to their use, redistribution, modification, or redistribution of derivative works of the code in this repository.

**To Reproduce**
1. Go to [netbox-circuitmaintenance on GitHub](https://github.com/jasonyates/netbox-circuitmaintenance)
2. Click on 'LICENSE' in the repository code browser
3. See that the `LICENSE` file is completely empty

**Expected behavior**
I expect to see the text of a license of the author's choosing.

**Screenshots**
Not necessary

**Additional context**
Hey, cool plugin! Hi there, I'm the product manager for NetBox Open Source at NetBox Labs. One of our customers has expressed an interest in this plugin being considered for inclusion in a certification program soon to be announced. One of the program criteria is that candidate plugins be distributed under an [OSI-approved license](https://opensource.org/licenses). If you prefer to discuss off GitHub, please DM me on NetDev Slack.

**Comment by jasonyates** [comment]
Apache 2.0 license has been added.
