### ISSUE TITLE
Update for netbox V4.X.X needed

### ISSUE THREAD

**Issue by ElonLP** [jasonyates/netbox-circuitmaintenance#22]
In netbox V4.X.X the "extras.plugins" now is called "netbox.plugins".

https://docs.netbox.dev/en/stable/plugins/development/migration-v4/

**Comment by cameronw1996** [comment]
+ 1

**Comment by andrey-zap81** [comment]
+1, any chance it will support v4?

**Comment by tbotnz** [comment]
+1

**Comment by jasonyates** [comment]
Hi,

I have just released version 0.4.0 with the following changes

* Adds support for Netbox 4.0 and 4.1
* Adds widget to show circuit maintenance events
* Updates styling to match new Netbox style

Thanks
