### ISSUE TITLE
Error when running upgrade script

### ISSUE THREAD

**Issue by cameronw1996** [jasonyates/netbox-circuitmaintenance#23]
**Plugin version**
0.3.0

**NetBox version**
3.7.1

**Describe the bug**
When running the NetBox upgrade.sh script, the following error is shown:

`django.db.migrations.exceptions.NodeNotFoundError: Migration netbox_documents.0006_vmdocument dependencies reference nonexistent parent node ('extras', '0106_bookmark_user_cascade_deletion')`

When the plugin in disabled in configuration file, upgrade script runs no problem. Plugin appears to still function without

**Comment by jasonyates** [comment]
Please raise this under the netbox-documents project.
